[project]
name = "pytorch-dlc"
version = "2.11.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "boto3",
    "botocore",
    "deepspeed==0.18.8",
    "fastai",
    "packaging",
    "pyyaml",
    "requests",
    "torch==2.11.0",
    "torchaudio==2.11.0",
    "torchvision==0.26.0",
]

[project.optional-dependencies]
# sagemaker = [
#     "smclarify",
#     "sagemaker>=3.4.0",
#     "sagemaker-pytorch-training",
#     "sagemaker-training",
#     "mlflow>=3.9.0",
#     "bokeh",
#     "imageio",
#     "numba",
#     "pandas",
#     "plotly",
#     "shap",
#     "scikit-learn",
#     "seaborn",
#     "cloudpickle",
#     "s3fs>=2026.2.0",
# ]

# workshop (installed in Docker runtime-base via: uv sync --extra workshop)
workshop = [
    "accelerate",
    "bokeh",
    "cloudpickle",
    "datasets>=4.0.0",
    "deepspeed",
    #"flash-attn-4[cu13]>=4.0.0b1",
    "flashinfer-jit-cache==0.6.8.post1+cu130",
    "hydra-core",
    "imageio",
    "mlflow>=3.9.0",
    "ninja",
    "numba",
    "numpy>=2.0.0",
    "omegaconf",
    "pandas",
    "peft",
    "plotly",
    "qwen_vl_utils==0.0.11",
    "ray[default,data,train]",
    "s3fs>=2026.2.0",
    "scikit-learn",
    "seaborn",
    "shap",
    "tensorboard",
    "tiktoken>=0.9.0",
    "torch-optimizer==0.3.0",
    "torch-tb-profiler",
    "torchinfo",
    "torchmetrics>=1.0.3",
    "tqdm>=4.66.0",
    "transformers>=4.45.0",
    "verl",
    "vllm>=0.20.1",
    #"wandb",
]

workshop-hyperpod = [
    "hyperpod-elastic-agent",
]

workshop-notebook = [
    "ipykernel>=6.25.0",
    "ipywidgets>=8.0.0",
    "jupyter>=1.0.0",
    "jupyterlab>=4.0.0",
    "matplotlib>=3.10.7",
    "nbdistributed==0.1.0",
    "notebook>=7.0.0",
    "seaborn>=0.13.2",
]

workshop-dev = [
    "black>=23.0.0",
    "flake8>=6.0.0",
    "isort>=5.12.0",
]

[tool.uv]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "vllm-nightly-cu130"
url = "https://wheels.vllm.ai/nightly/cu130"
explicit = true

[[tool.uv.index]]
name = "flashinfer-cu130"
url = "https://flashinfer.ai/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu130" }]
torchvision = [{ index = "pytorch-cu130" }]
torchaudio = [{ index = "pytorch-cu130" }]

vllm = [{ index = "vllm-nightly-cu130" }]
flashinfer-jit-cache = [{ index = "flashinfer-cu130" }]
